"""Generate Compose ImageVector sources from the same SVG sources used in Figma.

  design/icons/IconData*.kt  — Lucide line icons (+ custom Islamic line icons, brand marks)
  design/icons/GlyphData*.kt — duotone glyphs: colours are tokens S (stroke colour) / A (accent) resolved at runtime

Each shape becomes one path string, so the runtime builds an ImageVector with addPathNodes().
"""
import os, re, sys, json, math
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
from glyphs import GLYPH_FUNCS

OUT = os.path.join(ROOT, 'composeApp', 'src', 'commonMain', 'kotlin', 'com', 'deenjourney', 'app', 'design', 'icons')
os.makedirs(OUT, exist_ok=True)
NUM = lambda v: float(v) if v not in (None, '') else 0.0


def f(v):
    s = ('%.2f' % v).rstrip('0').rstrip('.')
    return '0' if s in ('-0', '') else s


def shape_to_d(el):
    tag = el.tag.split('}')[-1]
    a = el.attrib
    if tag == 'path':
        return a['d']
    if tag == 'circle':
        cx, cy, r = NUM(a.get('cx')), NUM(a.get('cy')), NUM(a.get('r'))
        return f'M{f(cx - r)} {f(cy)}a{f(r)} {f(r)} 0 1 0 {f(2 * r)} 0a{f(r)} {f(r)} 0 1 0 {f(-2 * r)} 0Z'
    if tag == 'ellipse':
        cx, cy, rx, ry = NUM(a.get('cx')), NUM(a.get('cy')), NUM(a.get('rx')), NUM(a.get('ry'))
        return f'M{f(cx - rx)} {f(cy)}a{f(rx)} {f(ry)} 0 1 0 {f(2 * rx)} 0a{f(rx)} {f(ry)} 0 1 0 {f(-2 * rx)} 0Z'
    if tag == 'rect':
        x, y, w, h = NUM(a.get('x')), NUM(a.get('y')), NUM(a.get('width')), NUM(a.get('height'))
        rx = NUM(a.get('rx') or a.get('ry'))
        if rx <= 0:
            return f'M{f(x)} {f(y)}h{f(w)}v{f(h)}h{f(-w)}Z'
        rx = min(rx, w / 2, h / 2)
        return (f'M{f(x + rx)} {f(y)}h{f(w - 2 * rx)}a{f(rx)} {f(rx)} 0 0 1 {f(rx)} {f(rx)}v{f(h - 2 * rx)}'
                f'a{f(rx)} {f(rx)} 0 0 1 {f(-rx)} {f(rx)}h{f(-(w - 2 * rx))}a{f(rx)} {f(rx)} 0 0 1 {f(-rx)} {f(-rx)}'
                f'v{f(-(h - 2 * rx))}a{f(rx)} {f(rx)} 0 0 1 {f(rx)} {f(-rx)}Z')
    if tag == 'line':
        return f'M{a["x1"]} {a["y1"]}L{a["x2"]} {a["y2"]}'
    if tag in ('polyline', 'polygon'):
        pts = re.findall(r'-?[\d.]+', a['points'])
        pairs = [f'{pts[i]} {pts[i + 1]}' for i in range(0, len(pts), 2)]
        return 'M' + 'L'.join(pairs) + ('Z' if tag == 'polygon' else '')
    return None


def walk(root):
    for el in root.iter():
        tag = el.tag.split('}')[-1]
        if tag in ('path', 'circle', 'ellipse', 'rect', 'line', 'polyline', 'polygon'):
            yield el


def kstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('$', '\\$') + '"'


def colour_token(v):
    """'#S' -> 'S', '#A' -> 'A', '#RRGGBB' -> 'xRRGGBB', none -> ''"""
    if not v or v == 'none':
        return ''
    if v in ('#S', '#A'):
        return v[1]
    if v.startswith('#') and len(v) == 7:
        return 'x' + v[1:].upper()
    return ''


def write_chunks(prefix, kind, entries, per=45):
    """entries: list of (name, kotlin_expr). Writes several files to stay well below JVM method limits."""
    files = []
    for i in range(0, len(entries), per):
        part = entries[i:i + per]
        nm = f'{prefix}{i // per}'
        body = ',\n'.join(f'    {kstr(n)} to {expr}' for n, expr in part)
        src = (f'// GENERATED by tools/art/gen_vectors.py — do not edit.\npackage com.deenjourney.app.design.icons\n\n'
               f'internal fun {nm}(): Map<String, {kind}> = mapOf(\n{body}\n)\n')
        open(os.path.join(OUT, nm + '.kt'), 'w', encoding='utf8').write(src)
        files.append(nm)
    return files


def main():
    # ---------- line icons ----------
    icons = json.load(open(os.path.join(ROOT, 'tools', 'figma', 'icons.json'), encoding='utf8'))
    ent = []
    for name in sorted(icons):
        root = ET.fromstring(icons[name])
        parts = []
        for el in walk(root):
            d = shape_to_d(el)
            if not d:
                continue
            fill = colour_token(el.attrib.get('fill'))
            parts.append(f'IP({kstr(d)}, {kstr(fill)})')
        ent.append((name, 'arrayOf(' + ', '.join(parts) + ')'))
    ifiles = write_chunks('iconData', 'Array<IP>', ent)

    # ---------- duotone glyphs ----------
    gent = []
    for name in sorted(GLYPH_FUNCS):
        svg = GLYPH_FUNCS[name]().text()
        root = ET.fromstring(svg)
        parts = []
        for el in walk(root):
            d = shape_to_d(el)
            if not d:
                continue
            a = el.attrib
            fill = colour_token(a.get('fill'))
            stroke = colour_token(a.get('stroke'))
            sw = float(a.get('stroke-width', '0') or 0) if stroke else 0.0
            op = float(a.get('opacity', '1'))
            fop = float(a.get('fill-opacity', '1'))
            parts.append(f'GP({kstr(d)}, {kstr(fill)}, {kstr(stroke)}, {f(sw)}f, {f(op * fop)}f)')
        gent.append((name, 'arrayOf(' + ', '.join(parts) + ')'))
    gfiles = write_chunks('glyphData', 'Array<GP>', gent)

    names = sorted(GLYPH_FUNCS)
    reg = ('// GENERATED by tools/art/gen_vectors.py — do not edit.\npackage com.deenjourney.app.design.icons\n\n'
           'internal val ICON_DATA: Map<String, Array<IP>> by lazy { ' + ' + '.join(f'{n}()' for n in ifiles) + ' }\n'
           'internal val GLYPH_DATA: Map<String, Array<GP>> by lazy { ' + ' + '.join(f'{n}()' for n in gfiles) + ' }\n\n'
           '/** All glyph names (duotone feature icons). */\n'
           'val GLYPH_NAMES: List<String> = listOf(' + ', '.join(kstr(n) for n in names) + ')\n')
    open(os.path.join(OUT, 'VectorRegistry.kt'), 'w', encoding='utf8').write(reg)
    print('icons', len(ent), 'files', len(ifiles), '· glyphs', len(gent), 'files', len(gfiles))


if __name__ == '__main__':
    main()
