// GENERATED by tools/art/gen_vectors.py — do not edit.
package com.deenjourney.app.design.icons

internal val ICON_DATA: Map<String, Array<IP>> by lazy { iconData0() + iconData1() + iconData2() + iconData3() }
internal val GLYPH_DATA: Map<String, Array<GP>> by lazy { glyphData0() + glyphData1() }

/** All glyph names (duotone feature icons). */
val GLYPH_NAMES: List<String> = listOf("adhkar", "akhlaq", "arafah", "arm", "audio", "bell", "body_side", "book_ribbon", "bookmark", "calendar", "check_all", "child", "download", "dua", "ears", "eid", "face", "fajr", "family", "fasting", "feet", "flag", "ghusl", "globe", "hadith", "hadith_day", "hands_wash", "head", "headphones", "heart", "help", "hifz", "iftar", "ihram", "intention", "isha", "jamarat", "kaaba", "kalima", "lantern", "leaf", "lesson", "luggage", "mat", "medal", "mic", "mosque", "mouth", "names", "nose", "note", "palm", "parent", "pebbles", "pillars", "prayer_time", "privacy_drop", "progress", "prophets", "qaida", "qibla", "quiz", "quran", "roadmap", "sai", "salah", "sawm", "scissors", "search", "sehri", "settings", "shahadah", "shield", "star", "story", "sun", "sun_low", "sunrise", "sunset", "sync", "tafsir", "tasbih", "tawaf", "telescope", "tent", "tracker", "wudu", "zakat")
